version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    ports: # Expose Elasticsearch ports
      - "9300:9300"
      - "9200:9200"
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node

  indexer:
    build: indexer/
    depends_on:
      - elasticsearch
    container_name: indexer

  api: # Node.js App
    container_name: api
    build: ./app
    ports:
      - "3000:3000" # Expose API port
      - "9229:9229" # Expose Node process debug port (disable in production)
    environment: # Set ENV vars
      - NODE_ENV=local
      - ES_HOST=elasticsearch
      - PORT=3000

  frontend: # Nginx Server For Frontend App
    container_name: frontend
    image: nginx
    volumes: # Serve local "public" dir
      - ./app/public:/usr/share/nginx/html
    ports:
      - "8080:80" # Forward site to localhost:8080

  kibana:
    image: 'docker.elastic.co/kibana/kibana:6.4.2'
    container_name: kibana
    environment:
      SERVER_NAME: kibana.local
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - '5601:5601'

